---
- name: Install Wordpress
  hosts: serverx
  remote_user: root
  vars:
   ansible_password: redhat

  tasks:
   - ping:
   - name: install httpd
     yum:
       name:
         - httpd
         - mariadb
         - mariadb-server
         - php
         - php-common 
         - php-mysql
         - php-gd
         - php-xml
         - php-mbstring
         - php-mcrypt
         - php-xmlrpc
         - python-pip 
       state: present
  
   - name: install mysql
     pip: 
       name: PyMySQL
       state: latest

   - name: start and enabled  httpd and mariadb
     service:
      name: "{{item.name}}"
      state: started
      enabled: yes
     loop:
      - { name: httpd}      
      - { name: mariadb}

   - name: firewall add-service permanent reload
     firewalld:
       service: http
       permanent: yes
       state: enabled
       immediate: yes

   - name: reload firewall
     command: firewall-cmd --reload

   - name: Set mariadb admin password
     block:
      - mysql_user:
         name: admin
         password: 'abc'
         state: present 
     rescue:
      - debug:
          msg: 'password has already'
 
   - name: Execute database dump file
     block:
      - name: Copy dumpfile     
        copy:
         src: dump.sql
         dest: /tmp/dump.sql
      - name: Execute
        mysql_db:
         state: import
         name: all
         target: /tmp/dump.sql
     rescue:
      - debug:
         msg: "has execute sql"
   - name: Download WordPress
     get_url:
       url: https://wordpress.org/wordpress-5.0.tar.gz
       dest: /tmp/wordpress.tar.gz

   - name: Extract WordPress
     unarchive: 
       src: /tmp/wordpress.tar.gz 
       dest: /var/www/html/
       remote_src: yes

   - name: Changing ownership
     file:
       path: /var/www/html/wordpress
       owner: apache
       group: apache

   - name: chmod add 755
     file: dest=/var/www/html/wordpress mode=755
     
   - name: Creates directory
     file:
      path: /var/www/html/wordpress/wp-content/uploads
      state: directory

   - name: Changing ownership uploads
     file:
       path: /var/www/html/wordpress/wp-content/uploads
       group: apache

   - name: move wp-config-sample.php
     command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
